"""
Deterministic machining calculator.
This is the SOURCE OF TRUTH for numbers — LLM never computes these itself,
it only extracts parameters from user text; this module does the real math.
"""

MATERIALS = {
    "aluminum": {"sfm": 300, "chip_load": 0.003},
    "mild_steel": {"sfm": 100, "chip_load": 0.002},
    "stainless_steel": {"sfm": 60, "chip_load": 0.0015},
}

VALID_MATERIALS = list(MATERIALS.keys())


def calculate_feeds_speeds(material: str, tool_diameter_mm: float, flutes: int = 2):
    material = material.lower().strip()
    if material not in MATERIALS:
        raise ValueError(
            f"Unknown material '{material}'. Supported: {VALID_MATERIALS}"
        )
    if tool_diameter_mm <= 0:
        raise ValueError("Tool diameter must be positive.")

    tool_diameter_in = tool_diameter_mm / 25.4
    sfm = MATERIALS[material]["sfm"]
    chip_load = MATERIALS[material]["chip_load"]

    rpm = (sfm * 12) / (3.14159 * tool_diameter_in)
    feed_rate_ipm = rpm * flutes * chip_load

    return {
        "rpm": round(rpm),
        "feed_rate_ipm": round(feed_rate_ipm, 2),
        "material": material,
        "tool_diameter_mm": tool_diameter_mm,
        "flutes": flutes,
        "sfm_used": sfm,
        "chip_load_used": chip_load,
    }


def generate_gcode(params: dict, hole_depth_mm: float = 10):
    depth_in = hole_depth_mm / 25.4
    gcode = f"""; Auto-generated by AI CAM Advisor - VERIFY BEFORE RUNNING
G21 ; mm mode
G90 ; absolute positioning
M03 S{params['rpm']} ; spindle on, RPM={params['rpm']}
G00 X0 Y0 Z5
G01 Z-{depth_in:.4f} F{params['feed_rate_ipm']} ; feed={params['feed_rate_ipm']} ipm
G00 Z5
M05 ; spindle off
M30 ; program end
"""
    return gcode


def safety_check(params: dict):
    warnings = []
    if params["rpm"] > 24000:
        warnings.append("RPM unusually high — check spindle max rating.")
    if params["feed_rate_ipm"] > 200:
        warnings.append("Feed rate unusually high — check for chatter/tool breakage risk.")
    if params["tool_diameter_mm"] < 1:
        warnings.append("Very small tool diameter — high snap risk, reduce feed further.")
    return warnings
